version: 2.1

orbs:
  react-native: react-native-community/react-native@4.4.2

jobs:
  checkout_code:
    executor: react-native/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .

  yarn_install:
    description: Install Javascript dependencies using Yarn. This command correctly configures the cache for any number of package.json and yarn.lock files.
    steps:
      - run:
          name: Create cache checksum file
          command: |
            mkdir -p ~/.tmp/checksumfiles
            find . -type f -name 'package.json' -not -path "*node_modules*" -exec cat {} + >> ~/.tmp/checksumfiles/package.json
            find . -type f -name 'yarn.lock' -not -path "*node_modules*" -exec cat {} + >> ~/.tmp/checksumfiles/yarn.lock
      - restore_cache:
          keys:
            - yarn-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}-{{ checksum "~/.tmp/checksumfiles/yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: Yarn Install
          command: yarn install --frozen-lockfile --non-interactive --cache-folder /tmp/yarn
      - save_cache:
          paths:
            - /tmp/yarn
          key: |
            yarn-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}-{{ checksum "~/.tmp/checksumfiles/yarn.lock" }}-{{ .Environment.CACHE_VERSION }}

workflows:
  test:
    jobs:
      - checkout_code
      - yarn_install:
          requires:
            - checkout_code
      - react-native/android_build:
          build_type: debug
          name: build_android_debug
          requires:
            - checkout_code
      - react-native/android_test:
          detox_configuration: android.emu.debug
          requires:
            - build_android_debug
            - yarn_install

